### PR TITLE
fix API version in CAPI kubeconfig

### PR DESCRIPTION
**Pull request by TylerGillson**

### CODE REVIEW

**Comment by spectro-prow** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/spectrocloud/cluster-api-provider-aws/pull/364#" title="Author self-approved">TylerGillson</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign  after the PR has been reviewed.
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=spectrocloud%2Fcluster-api-provider-aws).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/spectrocloud/cluster-api-provider-aws/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by sadysnaat** [comment]
@AmitSahastra is this change included in the v1beta1 branch?

**Comment by TylerGillson** [comment]
@sadysnaat can I merge this?

**Comment by sadysnaat** [comment]
We target our builds from v1beta1 branch we should raise it there

**Comment by TylerGillson** [comment]
> We target our builds from v1beta1 branch we should raise it there

My bad! Updated the base branch.

**Comment by TylerGillson** [comment]
@sadysnaat - safe to assume that these changes were handled elsewhere and I should close this PR?

**Comment by TylerGillson** [comment]
Handled in 374924fa632335ce17b0fe7648dc8e3a263b3169

**Pull request closed without merging**
